//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.18 at 11:19:40 AM CEST 
//


package com.ncr.eft.data.knet.requests;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "espRegisters"
})
@XmlRootElement(name = "Esp:Interface")
public class EspInterface {

    @XmlAttribute(name = "Version", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String version;
    @XmlAttribute(name = "xmlns:Esp")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String xmlnsEsp;
    @XmlElements({
        @XmlElement(name = "Esp:Admin", required = true, type = EspAdmin.class),
        //@XmlElement(name = "Esp:Error", required = true, type = EspError.class),
        @XmlElement(name = "Esp:Transaction", required = true, type = EspTransaction.class)
       // @XmlElement(name = "Esp:Event", required = true, type = EspEvent.class)
    })
    protected List<Object> espRegisters;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the xmlnsEsp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsEsp() {
        if (xmlnsEsp == null) {
            return "http://www.mosaicsoftware.com/Postilion/eSocket.POS/";
            //return "http://www.s1.com/Postilion/eSocket.POS/";
        } else {
            return xmlnsEsp;
        }
    }

    /**
     * Sets the value of the xmlnsEsp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsEsp(String value) {
        this.xmlnsEsp = value;
    }

    /**
     * Gets the value of the espAdminOrEspErrorOrEspTransactionOrEspInquiryOrEspCheckOrEspMerchandiseOrEspCallbackOrEspEventOrEspReconciliationOrEspNetwork property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the espAdminOrEspErrorOrEspTransactionOrEspInquiryOrEspCheckOrEspMerchandiseOrEspCallbackOrEspEventOrEspReconciliationOrEspNetwork property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEspAdminOrEspErrorOrEspTransactionOrEspInquiryOrEspCheckOrEspMerchandiseOrEspCallbackOrEspEventOrEspReconciliationOrEspNetwork().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EspAdmin }
     * {@link EspTransaction }
     * 
     *
     */
    public List<Object> getEspRegisters() {
        if (espRegisters == null) {
            espRegisters = new ArrayList<Object>();
        }
        return this.espRegisters;
    }

    public EspInterface() {
        setXmlnsEsp(getXmlnsEsp());
        setVersion("1");
        espRegisters= new ArrayList<Object>();
    }
}
