//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.18 at 11:19:40 AM CEST 
//


package com.ncr.eft.data.knet.responses.all;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = ""/*, propOrder = {
    "espPurchasingCardData",
    "espBalance",
    "espPosStructuredData",
    "espStructuredData",
    "espPayeeNameAndAddress",
    "espAdditionalPayeeInformation",
    "espAccountData"
}*/
)
@XmlRootElement(name = "Esp:Transaction")
public class EspTransactionResponse extends EspBasicResponse{

    @XmlAttribute(name = "TerminalId", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String terminalId;
    @XmlAttribute(name = "TransactionId", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String transactionId;
    @XmlAttribute(name = "Type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "LocalTime")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String localTime;
    @XmlAttribute(name = "LocalDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String localDate;
    @XmlAttribute(name = "RetrievalRefNr")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String retrievalRefNr;
    @XmlAttribute(name = "CardNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cardNumber;
    @XmlAttribute(name = "PanEntryMode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String panEntryMode;
    @XmlAttribute(name = "TransactionAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String transactionAmount;
    @XmlAttribute(name = "ResponseCode")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String responseCode;
    @XmlAttribute(name = "AuthorizationNumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String authorizationNumber;
    @XmlAttribute(name = "ActionCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String actionCode;
    @XmlAttribute(name = "CardProductName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cardProductName;
    @XmlAttribute(name = "MerchantId")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String merchantId;
    @XmlAttribute(name = "SignatureRequired")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String signatureRequired;
    @XmlAttribute(name = "EmvAmount")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String emvAmount;
    @XmlAttribute(name = "EmvApplicationIdentifier")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String emvApplicationIdentifier;
    @XmlAttribute(name = "EmvApplicationLabel")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String emvApplicationLabel;
    @XmlAttribute(name = "EmvTransactionDate")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String emvTransactionDate;

    /**
     * Gets the value of the terminalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminalId() {
        return terminalId;
    }

    /**
     * Sets the value of the terminalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminalId(String value) {
        this.terminalId = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the localTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalTime() {
        return localTime;
    }

    /**
     * Sets the value of the localTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalTime(String value) {
        this.localTime = value;
    }

    /**
     * Gets the value of the localDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalDate() {
        return localDate;
    }

    /**
     * Sets the value of the localDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalDate(String value) {
        this.localDate = value;
    }

    /**
     * Gets the value of the retrievalRefNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetrievalRefNr() {
        return retrievalRefNr;
    }

    /**
     * Sets the value of the retrievalRefNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetrievalRefNr(String value) {
        this.retrievalRefNr = value;
    }

    /**
     * Gets the value of the cardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * Sets the value of the cardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardNumber(String value) {
        this.cardNumber = value;
    }

    /**
     * Gets the value of the panEntryMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPanEntryMode() {
        return panEntryMode;
    }

    /**
     * Sets the value of the panEntryMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPanEntryMode(String value) {
        this.panEntryMode = value;
    }

    /**
     * Gets the value of the transactionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionAmount() {
        return transactionAmount;
    }

    /**
     * Sets the value of the transactionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionAmount(String value) {
        this.transactionAmount = value;
    }

    /**
     * Gets the value of the responseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseCode() {
        return responseCode;
    }

    /**
     * Sets the value of the responseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseCode(String value) {
        this.responseCode = value;
    }

    /**
     * Gets the value of the authorizationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorizationNumber() {
        return authorizationNumber;
    }

    /**
     * Sets the value of the authorizationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorizationNumber(String value) {
        this.authorizationNumber = value;
    }

    /**
     * Gets the value of the actionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionCode() {
        return actionCode;
    }

    /**
     * Sets the value of the actionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionCode(String value) {
        this.actionCode = value;
    }

    /**
     * Gets the value of the cardProductName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardProductName() {
        return cardProductName;
    }

    /**
     * Sets the value of the cardProductName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardProductName(String value) {
        this.cardProductName = value;
    }

    /**
     * Gets the value of the merchantId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * Sets the value of the merchantId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantId(String value) {
        this.merchantId = value;
    }

    /**
     * Gets the value of the signatureRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignatureRequired() {
        return signatureRequired;
    }

    /**
     * Sets the value of the signatureRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignatureRequired(String value) {
        this.signatureRequired = value;
    }

    /**
     * Gets the value of the emvAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmvAmount() {
        return emvAmount;
    }

    /**
     * Sets the value of the emvAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmvAmount(String value) {
        this.emvAmount = value;
    }

    /**
     * Gets the value of the emvApplicationIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmvApplicationIdentifier() {
        return emvApplicationIdentifier;
    }

    /**
     * Sets the value of the emvApplicationIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmvApplicationIdentifier(String value) {
        this.emvApplicationIdentifier = value;
    }

    /**
     * Gets the value of the emvApplicationLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmvApplicationLabel() {
        return emvApplicationLabel;
    }

    /**
     * Sets the value of the emvApplicationLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmvApplicationLabel(String value) {
        this.emvApplicationLabel = value;
    }

    /**
     * Gets the value of the emvTransactionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmvTransactionDate() {
        return emvTransactionDate;
    }

    /**
     * Sets the value of the emvTransactionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmvTransactionDate(String value) {
        this.emvTransactionDate = value;
    }

}
